package be.cytomine.appengine.dto.responses.errors;

public enum ErrorCode {
    /**
     * See ErrorDefinitions for code and message definitions
     */
    INTERNAL_TASK_EXISTS,
    INTERNAL_TASK_NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    INTERNAL_PARAMETER_LT_VALIDATION_ERROR,
    INTERNAL_PARAMETER_GT_VALIDATION_ERROR,
    INTERNAL_PARAMETER_LEQ_VALIDATION_ERROR,
    INTERNAL_PARAMETER_GEQ_VALIDATION_ERROR,
    INTERNAL_PARAMETER_DOES_NOT_EXIST,
    RUN_NOT_FOUND,
    INTERNAL_PARAMETER_VALIDATION_ERROR,
    INTERNAL_MULTIPLE_ERRORS,
    STORAGE_STORING_INPUT_FAILED,
    INTERNAL_GENERIC_BATCH_ERROR ,
    INTERNAL_INVALID_TASK_RUN_STATE,
    INTERNAL_PROVISIONS_NOT_FOUND ,
    INTERNAL_INVALID_OUTPUT,
    INTERNAL_MISSING_OUTPUTS,
    INTERNAL_UNKNOWN_OUTPUT,
    UKNOWN_STATE,
    INTERNAL_NOT_PROVISIONED,
    STORAGE_STORING_TASK_DEFINITION_FAILED,
    REGISTRY_PUSHING_TASK_IMAGE_FAILED,
    INTERNAL_UNKNOWN_BUNDLE_ARCHIVE_FORAMT,
    INTERNAL_UNKNOWN_IMAGE_ARCHIVE_FORMAT,
    INTERNAL_DESCRIPTOR_EXTRACTION_FAILED,
    INTERNAL_DOCKER_IMAGE_EXTRACTION_FAILED,
    INTERNAL_DESCRIPTOR_NOT_IN_DEFAULT_LOCATION,
    INTERNAL_DOCKER_IMAGE_TAR_NOT_FOUND,
    STORAGE_CREATING_STORAGE_FAILED,
    INTERNAL_SCHEMA_VALIDATION_ERROR,
    INTERNAL_DOCKER_IMAGE_MANIFEST_MISSING,
    INTERNAL_MAX_UPLOAD_SIZE_EXCEEDED, INTERNAL_INVALID_BUNDLE_FORMAT, INTERNAL_PARAMETER_SCHEMA_VALIDATION_ERROR
}
